name: Train AML Model on SageMaker

on:
  push:
    branches: [main]

jobs:
  train-on-sagemaker:
    runs-on: ubuntu-22.04 # We use a fix ubentu ver stinead of ubuntu-latest as it is stable and fully supported

    env:
      AWS_REGION: us-east-2

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Upload dataset to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          python -c "from s3_utils import upload_to_s3; \
            upload_to_s3('data/Big_Black_Money_Dataset.csv', 'aml-model-bk', 'data/Big_Black_Money_Dataset.csv')"

      - name: Launch SageMaker training job
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          python sagemaker_launcher.py
